### ISSUE TITLE
komo inztalo paiton?

### ISSUE THREAD

**Issue by x4rvm** [xLoadCode/xLoadCode-Tool#1]
pregunta seria

**Comment by BlackVirus12** [comment]
eZ l4 tul de masonr4pa?

**Comment by x4rvm** [comment]
@BlackVirus12 Y si mejor te suicidas, anormal de mierda.

Yo ando preguntando algo serio y vienes con tus mamadas de masonrata.

**Comment by BlackVirus12** [comment]
😔😔

**Comment by x4rvm** [comment]
@xLoadCode Responde no seas gay

**Comment by x4rvm** [comment]
Vendo

**Comment by x4rvm** [comment]
Compro
